apiVersion: v1
kind: Secret
metadata:
  name: shorty-secrets
  namespace: shorty
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=
  jwt-secret-key: ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24tMTIzNDU=
  # admin@shorty.com -> YWRtaW5Ac2hvcnR5LmNvbQ==
  pgadmin-email: YWRtaW5Ac2hvcnR5LmNvbQ==
  # admin -> YWRtaW4=
  pgadmin-password: YWRtaW4=
